site_name: Awesome Mojo
site_url: https://awesome-mojo.com
site_description: A curated list of awesome Mojo frameworks, libraries and software
site_author: Related Code
repo_name: relatedcode/awesome-mojo
repo_url: https://github.com/relatedcode/awesome-mojo
theme:
  name: material
  palette:
    primary: red
    accent: pink
extra:
  social:
    - type: github
      link: https://github.com/relatedcode
extra_css:
    - css/extra.css
nav:
  - "Life is short, you need Mojo.": "index.md"
